### ISSUE TITLE
Refactor stylesheets & Myth usage

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/chriszuber#57]
For development in supoprted browsers, use `combined.css`
Otherwise, use Myth output.

`combined.css` should now be similar to:
```CSS
@charset 'UTF-8';
@import 'normalize.css';
@import ...
:root {
    --css-var: 'var value';
    ....
}
```

Remove all `*.out.css`
