### ISSUE TITLE
Use class rules where appropriate

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/chriszuber#78]
For example:
Instead of
```CSS
header nav {
    display: flex;
    ...
}
```
just add the appropriate class.
